# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
fortran: false
latex: false
pandoc: false

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: oldrel
    - r: release
      r_packages: covr
      r_github_packages: jimhester/lintr
      env: R_CODECOV=true R_LINTR=true
    - r: devel
    - os: osx
      brew_packages: libgit2
    - os: osx
      disable_homebrew: true
    - os: osx
      disable_homebrew: true
      env: autobrew=yes

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

after_success:
  - test ${R_CODECOV} && Rscript -e "covr::coveralls(exclusions=list.files('src/libgit2', pattern='[.](c|h)$', full.names=TRUE, recursive=TRUE))"
  - test ${R_LINTR} && Rscript -e "lintr::lint_package(linters = lintr::with_defaults(object_name_linter = NULL, object_usage_linter = NULL))"
  - cat "${RCHECK_DIR}/00install.out"

notifications:
  slack:
    secure: AGzcnnQM/zF7+8XLzai8uuOC0Ll6E1jChN5FsXZU+02NY1KrpGYG7IQgui0ZDQW5NNGIlSHuz3GBP0J1Ku7RdGi/uTEG8sEnmtAf0IGvWzr2Db2jN8KbVqcQAvqt5XTwS1VHgY0wOwXcaTqIG4KhpRdA6Mae/PkUhbHuv2GjgmE=
